name: Build

on: [workflow_dispatch]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:

  Archiving:
    runs-on: ubuntu-latest
    needs: [buildAndroidAPK, buildAndroidAAB]
    steps:
    
      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        with:
             name: build-Android
             path: ${{ github.workspace }}/build/Android
             
      - uses: vimtor/action-zip@v1
        with:
            files: build/Android
            dest: project_folder/${{ secrets.APP_NAME }}.zip
            
      - uses: geekyeggo/delete-artifact@v1
        with:
            name: build-Android
                
      - uses: actions/upload-artifact@v1
        with:
           name: ${{ secrets.APP_NAME }}
           path: ${{ github.workspace }}/project_folder/${{ secrets.APP_NAME }}.zip
           
  SendTelegramNotify:
    runs-on: ubuntu-latest
    needs: Archiving
    name: Send Telegram Notify
    
    steps: 
      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        id: download
        with:
            name: ${{ secrets.APP_NAME }}
            path: ${{ github.workspace }}/project_folder
            
      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
              to: ${{ secrets.TELEGRAM_ID }}
              token: ${{ secrets.TELEGRAM_TOKEN }}
              message: " "
              document: '${{ github.workspace }}/project_folder/${{ secrets.APP_NAME }}.zip'
              
      - uses: geekyeggo/delete-artifact@v1
        with:
            name: ${{ secrets.APP_NAME }}
      

  buildAndroidAPK:
    name: Build for Android(APK)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - Android
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2.4.2
          
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
          
      - uses: game-ci/unity-builder@v2.0.4
        with:
          androidAppBundle: false
          androidKeystoreName: user.keystore
          androidKeystoreBase64: "/u3+7QAAAAIAAAABAAAAAQAEcXVhbgAAAYNMzh6VAAAFATCCBP0wDgYKKwYBBAEqAhEBAQUABIIE6eXpdUUsdv+qvEVBn+W3hwEXxnowtpYl4umJMUdT2WXxzASnW0sYFtWzDIoUvy8td1/etczkX8LBol3KVaqU1fdKzlN398OMpWiDg8jCcjAzB9IpA2CWntJNwuZVUqAKm7NcupxYPAmuLIMlFWjhOHWImjaB1FVgwlJLVIC+nnUjG9JMNlcnHPQXe1aU++A1MosAA0F+4AqgkhXljH1z4WBTk2Uzcu/8bBQtUiIIYjen+m35QeFH9lRH2dfVGZ8sgQVio9cghxi9kX7VuLIX8ZeukVsEFCel64lBcNl2vn52ey5HGUWwi7v/DZVLLJSuMG2JQxBb792EsW0KX8XgFjC5dRI6eUaFfPR/wZGfMOtWYF+6U/SsXxfZDdgUS7Rd/Kmh18KksPML6kea2uiDbpZXioCPzTd94jHbeEccX4ApwX5Lc03V4iqvRK6yjcFylGebLLVCLflyuDD403k35WvxWoMupX5CH0hyWSFljXlQzHPK7oW5h249AcdJSJTDcyWXDI/0uWBYnCJwAB2JRYSF1yThYGrIUsENOZ0gSBQix+tV58jd8MDYlGR97rSxTWSVp8jToJUtp1RBFPegOOdrr5jQsUmVx6ERa6qdn71gkOQacfSLadJbJ8CHFzDQcHjvz/5vsdazneV0FYEZ9op7V/Eu+/XOJPiRyJxx+Hco/78l/uIogEGNO3G8xUKA09zwCFoOWNMLQoffg8P7sfThVG/xtVxAp9XW8mpXZz5nWNTTdAtqppuGvWPZxJAqEiHkfekZyuswZiM/FHIyRdHuPL7IegQDirwIzzW2CRJ3gxl6U+zFPGU/Mr6piK2dYuQx8Xy3wLN/31BlBKrhBbnz6scQUmQllGPbFFVmfZnc47eGOewgZK2oxgTW8JOx9fwI1U1lUJfLBmFhEYP4+UrXE14sRh2ELtwtOREnT+CBWlzroBy+QN0zRxz/65+8jH4m54OA/T8VsHzWJbTlUvg6q6HkimI+H6mi1LmyUO6BB2/082xC7xwjxp0OJCpMa3192Y3hURpRoIzu4XZ7vmeoHTpKC7zpS/+syxdT/5QWTCS1n11ICfhUS9GF7g9KecC2kHRbtloCyeVXkydEIx5DkPgFoPngrV6jcJ64x7TiWl940Oiq50O2gACN0RVnNevLOrncfswnhhRJS4GPYBtRM423Y7F6nDx0cmj/UY5fnfveU/n9DZGdM9VLrdAafK0IaWkpvD4CyUTn5RjVUfDGLcfLp1ByTsrzQbXMNovb51L+KX2p+Kx9MG4xYz0Q2NQh1DYrt/x4FoSCTzLgtW5DbJy04VLJN3Ozh4s2wqgovSc5B6wndQJy1eEKvnoI1nm/tBaobt5/VVzJHWWexed791EZs2E8dYWspsjguyNI1fQd83sAVD1kGdSr9YWREK50UFlgdXHki5e/EcmGoFtkr7FRLD9zJnwpfJEw/r5pXwo+uLhE5xBzAGaE9Ma7XQtGG1AtjuRUFYJNWYinIRywhZcI1miXGaDIkZ8h6pKCSK2YGQBtwQfAHbj26o70IAYUotANlJ+Luh/P2uvg2CNTDlEYEa/5/9S4M4tYyLcvIh1ZQrfA3w2S1EmqglqOusgZSUArUlky5mkIufmPU8o/mYt/jcTxlg6C6GiD2cEMpqO2NIoBZ3C2sXK445uHAGqNNvYDZeSQRQAAAAEABVguNTA5AAACoDCCApwwggGEoAMCAQICBFJsXwkwDQYJKoZIhvcNAQEFBQAwDzENMAsGA1UECgwEUXVhbjAgFw0yMjA5MTcxODU1MjBaGA8yMDcyMDkwNDE4NTUyMFowDzENMAsGA1UECgwEUXVhbjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKIQVvTbJfrTHcfb2xuwPfnk3ywT58Yggks7pXiHMaQBNHfgKkAyr7Rc3WeToT//1c/zwz31G98KfP7aRgR5dcnvi6DTbZ9NazNRdDBG19wLf4nvFS4UcpZhM+yG0QAfg9XxUc0sQ3iU/UPuMXPk1ThS0RKdk0Lm+bnQPB+rTfokDGHvN/MdeMUikDHgJyM9ppINpYJYQEN7zmxI23l/RFAOlEdMNv9iQ2SDj7OfjZgOGOAkCucQIoZiT/LfA8tV5NZ+tzMq9SpkWeY4PncdpSQTpISvg4jkR7AtWEGOx3aqlZOCDbH/9Ofsprr1Lx1tqemZ3su0qoKmy36BZ5W/PtkCAwEAATANBgkqhkiG9w0BAQUFAAOCAQEAKIOs+IBQYsMNi1PKR0pg29/0RcncS7wR1lNB3/yCUTFW/q0QIBgJNXCrKsbKC3fviUGLaGXaVES0Eh+GNm5pN/gF+cUBBpsexi4RJ0Jp/78xbIcnyx70uiaRnJQOeZK8JVbIzd92AMbYRzfg2bqoMSd7y/Tqyvz1vYa1TRi4jnTvwU+swInIe4C5UQecXEuI0Wiq32YE1H+ZaaCRVScG3rapkw9JBvZk8h3vgM4AtH6wF9Aq2frw6LpfwHGWpo/c60JMy5IlDE6gPvk/YPVhL62Ae/ANEz1YuR1a3AM2J9Qn9uBujqY2ERqPefB94MwRQYOmfZotDOYmABJGy3cZBo4TqQTVaEq7omOEwik6ejrcjpey"
          androidKeystorePass: "UreiO8Q11&P!"
          androidKeyaliasName: "quan"
          androidKeyaliasPass: "UreiO8Q11&P!"
          targetPlatform: ${{ matrix.targetPlatform }}
          
      - uses: actions/upload-artifact@v2
        with:
          name: build-Android
          path: build/Android
          
  buildAndroidAAB:
    name: Build for Android(AAB)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - Android
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
          
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
          
      - uses: game-ci/unity-builder@v2.0.4
        with:
          androidAppBundle: true
          androidKeystoreName: user.keystore
          androidKeystoreBase64: "/u3+7QAAAAIAAAABAAAAAQAEcXVhbgAAAYNMzh6VAAAFATCCBP0wDgYKKwYBBAEqAhEBAQUABIIE6eXpdUUsdv+qvEVBn+W3hwEXxnowtpYl4umJMUdT2WXxzASnW0sYFtWzDIoUvy8td1/etczkX8LBol3KVaqU1fdKzlN398OMpWiDg8jCcjAzB9IpA2CWntJNwuZVUqAKm7NcupxYPAmuLIMlFWjhOHWImjaB1FVgwlJLVIC+nnUjG9JMNlcnHPQXe1aU++A1MosAA0F+4AqgkhXljH1z4WBTk2Uzcu/8bBQtUiIIYjen+m35QeFH9lRH2dfVGZ8sgQVio9cghxi9kX7VuLIX8ZeukVsEFCel64lBcNl2vn52ey5HGUWwi7v/DZVLLJSuMG2JQxBb792EsW0KX8XgFjC5dRI6eUaFfPR/wZGfMOtWYF+6U/SsXxfZDdgUS7Rd/Kmh18KksPML6kea2uiDbpZXioCPzTd94jHbeEccX4ApwX5Lc03V4iqvRK6yjcFylGebLLVCLflyuDD403k35WvxWoMupX5CH0hyWSFljXlQzHPK7oW5h249AcdJSJTDcyWXDI/0uWBYnCJwAB2JRYSF1yThYGrIUsENOZ0gSBQix+tV58jd8MDYlGR97rSxTWSVp8jToJUtp1RBFPegOOdrr5jQsUmVx6ERa6qdn71gkOQacfSLadJbJ8CHFzDQcHjvz/5vsdazneV0FYEZ9op7V/Eu+/XOJPiRyJxx+Hco/78l/uIogEGNO3G8xUKA09zwCFoOWNMLQoffg8P7sfThVG/xtVxAp9XW8mpXZz5nWNTTdAtqppuGvWPZxJAqEiHkfekZyuswZiM/FHIyRdHuPL7IegQDirwIzzW2CRJ3gxl6U+zFPGU/Mr6piK2dYuQx8Xy3wLN/31BlBKrhBbnz6scQUmQllGPbFFVmfZnc47eGOewgZK2oxgTW8JOx9fwI1U1lUJfLBmFhEYP4+UrXE14sRh2ELtwtOREnT+CBWlzroBy+QN0zRxz/65+8jH4m54OA/T8VsHzWJbTlUvg6q6HkimI+H6mi1LmyUO6BB2/082xC7xwjxp0OJCpMa3192Y3hURpRoIzu4XZ7vmeoHTpKC7zpS/+syxdT/5QWTCS1n11ICfhUS9GF7g9KecC2kHRbtloCyeVXkydEIx5DkPgFoPngrV6jcJ64x7TiWl940Oiq50O2gACN0RVnNevLOrncfswnhhRJS4GPYBtRM423Y7F6nDx0cmj/UY5fnfveU/n9DZGdM9VLrdAafK0IaWkpvD4CyUTn5RjVUfDGLcfLp1ByTsrzQbXMNovb51L+KX2p+Kx9MG4xYz0Q2NQh1DYrt/x4FoSCTzLgtW5DbJy04VLJN3Ozh4s2wqgovSc5B6wndQJy1eEKvnoI1nm/tBaobt5/VVzJHWWexed791EZs2E8dYWspsjguyNI1fQd83sAVD1kGdSr9YWREK50UFlgdXHki5e/EcmGoFtkr7FRLD9zJnwpfJEw/r5pXwo+uLhE5xBzAGaE9Ma7XQtGG1AtjuRUFYJNWYinIRywhZcI1miXGaDIkZ8h6pKCSK2YGQBtwQfAHbj26o70IAYUotANlJ+Luh/P2uvg2CNTDlEYEa/5/9S4M4tYyLcvIh1ZQrfA3w2S1EmqglqOusgZSUArUlky5mkIufmPU8o/mYt/jcTxlg6C6GiD2cEMpqO2NIoBZ3C2sXK445uHAGqNNvYDZeSQRQAAAAEABVguNTA5AAACoDCCApwwggGEoAMCAQICBFJsXwkwDQYJKoZIhvcNAQEFBQAwDzENMAsGA1UECgwEUXVhbjAgFw0yMjA5MTcxODU1MjBaGA8yMDcyMDkwNDE4NTUyMFowDzENMAsGA1UECgwEUXVhbjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKIQVvTbJfrTHcfb2xuwPfnk3ywT58Yggks7pXiHMaQBNHfgKkAyr7Rc3WeToT//1c/zwz31G98KfP7aRgR5dcnvi6DTbZ9NazNRdDBG19wLf4nvFS4UcpZhM+yG0QAfg9XxUc0sQ3iU/UPuMXPk1ThS0RKdk0Lm+bnQPB+rTfokDGHvN/MdeMUikDHgJyM9ppINpYJYQEN7zmxI23l/RFAOlEdMNv9iQ2SDj7OfjZgOGOAkCucQIoZiT/LfA8tV5NZ+tzMq9SpkWeY4PncdpSQTpISvg4jkR7AtWEGOx3aqlZOCDbH/9Ofsprr1Lx1tqemZ3su0qoKmy36BZ5W/PtkCAwEAATANBgkqhkiG9w0BAQUFAAOCAQEAKIOs+IBQYsMNi1PKR0pg29/0RcncS7wR1lNB3/yCUTFW/q0QIBgJNXCrKsbKC3fviUGLaGXaVES0Eh+GNm5pN/gF+cUBBpsexi4RJ0Jp/78xbIcnyx70uiaRnJQOeZK8JVbIzd92AMbYRzfg2bqoMSd7y/Tqyvz1vYa1TRi4jnTvwU+swInIe4C5UQecXEuI0Wiq32YE1H+ZaaCRVScG3rapkw9JBvZk8h3vgM4AtH6wF9Aq2frw6LpfwHGWpo/c60JMy5IlDE6gPvk/YPVhL62Ae/ANEz1YuR1a3AM2J9Qn9uBujqY2ERqPefB94MwRQYOmfZotDOYmABJGy3cZBo4TqQTVaEq7omOEwik6ejrcjpey"
          androidKeystorePass: "UreiO8Q11&P!"
          androidKeyaliasName: "quan"
          androidKeyaliasPass: "UreiO8Q11&P!"
          targetPlatform: ${{ matrix.targetPlatform }}
          
      - uses: actions/upload-artifact@v2
        with:
          name: build-Android
          path: build/Android
